/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  darkMode: 'class',
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        diabetactic: {
          primary: '#25aff4',
          'primary-content': '#ffffff',
          secondary: '#00c6ae',
          'secondary-content': '#ffffff',
          accent: '#667eea',
          'accent-content': '#ffffff',
          neutral: '#0d171c',
          'neutral-content': '#ffffff',
          'base-100': '#ffffff',
          'base-200': '#f5f7f8',
          'base-300': '#e5e7eb',
          'base-content': '#0d171c',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#22c55e',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#000000',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
        dark: {
          primary: '#25aff4',
          'primary-content': '#ffffff',
          secondary: '#00c6ae',
          'secondary-content': '#ffffff',
          accent: '#667eea',
          'accent-content': '#ffffff',
          neutral: '#1e293b',
          'neutral-content': '#ffffff',
          'base-100': '#101c22',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#ffffff',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#22c55e',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#000000',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
      },
    ],
    darkTheme: 'dark',
    logs: false,
  },
};
