/**
 * Global Lucide Icons Registry - OPTIMIZED
 *
 * This file exports only the Lucide icons actually used via app-icon component.
 * OPTIMIZED: Reduced from 292 to 49 icons (~83% reduction)
 *
 * Date optimized: 2025-12-07
 */

import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Apple,
  ArrowLeft,
  ArrowUp,
  Award,
  Bell,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Clock,
  ClipboardList,
  Cloud,
  Contrast,
  Droplet,
  Dumbbell,
  FilePlus,
  FileText,
  Filter,
  Flame,
  Footprints,
  Heart,
  Info,
  Languages,
  Lightbulb,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  MessageSquare,
  Minus,
  Moon,
  Pill,
  Plus,
  RefreshCw,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Smile,
  Stethoscope,
  Syringe,
  Trash2,
  TrendingUp,
  Trophy,
  Users,
  UtensilsCrossed,
  UserPlus,
  Wifi,
  X,
} from 'lucide-angular';

/**
 * Collection of application icons (only used icons)
 * Usage: LucideAngularModule.pick(appIcons)
 */
export const appIcons = {
  Activity,
  AlertCircle,
  AlertTriangle,
  Apple,
  ArrowLeft,
  ArrowUp,
  Award,
  Bell,
  Bug,
  Calendar,
  CalendarCheck,
  CalendarPlus,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  Clock,
  ClipboardList,
  Cloud,
  Contrast,
  Droplet,
  Dumbbell,
  FilePlus,
  FileText,
  Filter,
  Flame,
  Footprints,
  Heart,
  Info,
  Languages,
  Lightbulb,
  Loader,
  LoaderCircle,
  Lock,
  LogOut,
  MessageSquare,
  Minus,
  Moon,
  Pill,
  Plus,
  RefreshCw,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Smile,
  Stethoscope,
  Syringe,
  Trash2,
  TrendingUp,
  Trophy,
  Users,
  UtensilsCrossed,
  UserPlus,
  Wifi,
  X,
};

/**
 * Icon name mappings from Ionicons to Lucide
 * Internal reference for template migration (not exported)
 * @internal
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _iconMappings = {
  'save-outline': 'save',
  'chevron-forward': 'chevron-right',
  'chevron-forward-outline': 'chevron-right',
  'chevron-down': 'chevron-down',
  add: 'plus',
  'download-outline': 'download',
  'bug-outline': 'bug',
  bug: 'bug',
  'settings-outline': 'settings',
  'log-out-outline': 'log-out',
  'trash-outline': 'trash-2',
  trash: 'trash-2',
  checkmark: 'check',
  'checkmark-circle': 'check-circle',
  'location-outline': 'map-pin',
  star: 'star',
  'calendar-outline': 'calendar',
  'time-outline': 'clock',
  'analytics-outline': 'bar-chart-3',
  'sync-outline': 'refresh-cw',
  'help-circle-outline': 'help-circle',
  'person-circle-outline': 'user-circle',
  'alert-circle-outline': 'alert-circle',
  'flask-outline': 'flask',
  reload: 'rotate-cw',
  warning: 'alert-triangle',
  close: 'x',
} as const;
