import { Component, CUSTOM_ELEMENTS_SCHEMA, Input, ChangeDetectionStrategy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule } from 'lucide-angular';

@Component({
  selector: 'app-icon',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [CommonModule, LucideAngularModule],
  template: `
    <lucide-icon
      [name]="mappedName"
      [ngClass]="computedClasses"
      [size]="computedSize"
      [attr.aria-hidden]="ariaLabel ? null : 'true'"
      [attr.aria-label]="ariaLabel || null"
      [attr.role]="ariaLabel ? 'img' : null"
    >
    </lucide-icon>
  `,
  styles: [],
})
export class AppIconComponent {
  @Input() name = '';
  @Input() size: 'xs' | 'sm' | 'md' | 'lg' | 'xl' = 'md';
  @Input() class = '';
  @Input() ariaLabel = ''; // For accessible icons that need labels

  // Icon name mappings from Ionicons to Lucide
  private iconMappings: Record<string, string> = {
    'save-outline': 'save',
    'arrow-back': 'arrow-left',
    'arrow-back-outline': 'arrow-left',
    'chevron-back': 'chevron-left',
    'chevron-forward': 'chevron-right',
    'chevron-forward-outline': 'chevron-right',
    'chevron-down': 'chevron-down',
    'chevron-down-outline': 'chevron-down',
    add: 'plus',
    'add-outline': 'plus',
    'add-circle-outline': 'plus-circle',
    'download-outline': 'download',
    'bug-outline': 'bug',
    'settings-outline': 'settings',
    settings: 'settings',
    'calculator-outline': 'calculator',
    calculator: 'calculator',
    'log-out-outline': 'log-out',
    'trash-outline': 'trash-2',
    trash: 'trash-2',
    checkmark: 'check',
    'checkmark-outline': 'check',
    'checkmark-circle': 'check-circle',
    'checkmark-circle-outline': 'check-circle',
    barcode: 'barcode',
    'barcode-outline': 'barcode',
    'clipboard-check': 'clipboard-check',
    'location-outline': 'map-pin',
    star: 'star',
    'star-outline': 'star',
    'calendar-outline': 'calendar',
    calendar: 'calendar',
    'time-outline': 'clock',
    time: 'clock',
    'analytics-outline': 'bar-chart-3',
    analytics: 'bar-chart-3',
    'sync-outline': 'refresh-cw',
    sync: 'refresh-cw',
    'help-circle-outline': 'help-circle',
    'help-circle': 'help-circle',
    'person-circle-outline': 'user-circle',
    'person-circle': 'user-circle',
    'alert-circle-outline': 'alert-circle',
    'alert-circle': 'alert-circle',
    'flask-outline': 'flask-conical',
    flask: 'flask-conical',
    reload: 'rotate-cw',
    'reload-outline': 'rotate-cw',
    warning: 'alert-triangle',
    'warning-outline': 'alert-triangle',
    close: 'x',
    'close-outline': 'x',
    'close-circle': 'x-circle',
    'close-circle-outline': 'x-circle',
    'medical-outline': 'stethoscope',
    medical: 'stethoscope',
    'person-outline': 'user',
    person: 'user',
    'lock-closed-outline': 'lock',
    'lock-closed': 'lock',
    'eye-outline': 'eye',
    eye: 'eye',
    'eye-off-outline': 'eye-off',
    'eye-off': 'eye-off',
    'videocam-outline': 'video',
    videocam: 'video',
    'filter-outline': 'filter',
    filter: 'filter',
    'arrow-up': 'arrow-up',
    'arrow-up-outline': 'arrow-up',
    'arrow-down': 'arrow-down',
    'arrow-down-outline': 'arrow-down',
    'share-outline': 'share-2',
    share: 'share-2',
    wifi: 'wifi',
    'wifi-outline': 'wifi',
    'cloud-offline': 'cloud-off',
    'cloud-offline-outline': 'cloud-off',
    'nuclear-outline': 'alert-triangle',
    nuclear: 'alert-triangle',
    'copy-outline': 'copy',
    copy: 'copy',
    'document-text-outline': 'file-text',
    'document-text': 'file-text',
    description: 'file-text', // Material Symbols description icon
    'shield-checkmark-outline': 'shield-check',
    'shield-checkmark': 'shield-check',
    'contrast-outline': 'contrast',
    contrast: 'contrast',
    'language-outline': 'languages',
    language: 'languages',
    'water-outline': 'droplet',
    water: 'droplet',
    'accessibility-outline': 'accessibility',
    accessibility: 'accessibility',
    'medkit-outline': 'heart',
    medkit: 'heart',
    'information-circle-outline': 'info',
    'information-circle': 'info',
    'moon-outline': 'moon',
    moon: 'moon',
    'sunny-outline': 'sun',
    sunny: 'sun',
    'clipboard-outline': 'clipboard',
    clipboard: 'clipboard',
    'create-outline': 'edit-3',
    create: 'edit-3',
    'pencil-outline': 'edit-2',
    pencil: 'edit-2',
    'search-outline': 'search',
    search: 'search',
    'expand-outline': 'maximize-2',
    expand: 'maximize-2',
    'contract-outline': 'minimize-2',
    contract: 'minimize-2',
    'home-outline': 'home',
    home: 'home',
    'refresh-outline': 'refresh-cw',
    refresh: 'refresh-cw',
    'call-outline': 'phone',
    call: 'phone',
    'mail-outline': 'mail',
    mail: 'mail',
    'notifications-outline': 'bell',
    notifications: 'bell',
    'camera-outline': 'camera',
    camera: 'camera',
    'mic-outline': 'mic',
    mic: 'mic',
    'volume-high-outline': 'volume-2',
    'volume-high': 'volume-2',
    'play-outline': 'play',
    play: 'play',
    'pause-outline': 'pause',
    pause: 'pause',
    'stop-outline': 'square',
    stop: 'square',
    'heart-outline': 'heart',
    heart: 'heart',
    'thumbs-up-outline': 'thumbs-up',
    'thumbs-up': 'thumbs-up',
    'thumbs-down-outline': 'thumbs-down',
    'thumbs-down': 'thumbs-down',
    'globe-outline': 'globe',
    globe: 'globe',
    'link-outline': 'link',
    link: 'link',
    'attach-outline': 'paperclip',
    attach: 'paperclip',
    'bookmark-outline': 'bookmark',
    bookmark: 'bookmark',
    'folder-outline': 'folder',
    folder: 'folder',
    'folder-open-outline': 'folder-open',
    'folder-open': 'folder-open',
    'git-branch-outline': 'git-branch',
    'git-branch': 'git-branch',
    'git-commit-outline': 'git-commit',
    'git-commit': 'git-commit',
    'git-merge-outline': 'git-merge',
    'git-merge': 'git-merge',
    'git-pull-request-outline': 'git-pull-request',
    'git-pull-request': 'git-pull-request',
    'code-outline': 'code',
    code: 'code',
    'terminal-outline': 'terminal',
    terminal: 'terminal',
    'server-outline': 'server',
    server: 'server',
    'database-outline': 'database',
    database: 'database',
    'cloud-outline': 'cloud',
    cloud: 'cloud',
    'cloud-upload-outline': 'upload-cloud',
    'cloud-upload': 'upload-cloud',
    'cloud-download-outline': 'download-cloud',
    'cloud-download': 'download-cloud',
    // Shape mappings
    ellipse: 'circle',
    'ellipse-outline': 'circle',
    // Spinner mappings
    crescent: 'loader',
    circular: 'loader-circle',
    dots: 'loader',
    bubbles: 'loader',
    lines: 'loader',
    // Material Symbols mappings
    arrow_back: 'arrow-left',
    arrow_forward: 'arrow-right',
    more_vert: 'more-vertical',
    more_horiz: 'more-horizontal',
    done: 'check',
    clear: 'x',
    edit: 'edit-2',
    delete: 'trash-2',
    visibility: 'eye',
    visibility_off: 'eye-off',
    lock: 'lock',
    lock_open: 'unlock',
    account_circle: 'user-circle',
    logout: 'log-out',
    login: 'log-in',
    remove: 'minus',
    expand_more: 'chevron-down',
    expand_less: 'chevron-up',
    chevron_left: 'chevron-left',
    chevron_right: 'chevron-right',
    menu: 'menu',
    filter_list: 'filter',
    sort: 'arrow-up-down',
    upload: 'upload',
    download: 'download',
    print: 'printer',
    favorite: 'heart',
    dashboard: 'layout-dashboard',
    message: 'message-square',
    email: 'mail',
    phone: 'phone',
    calendar_today: 'calendar',
    schedule: 'clock',
    alarm: 'alarm-clock',
    location_on: 'map-pin',
    map: 'map',
    directions: 'navigation',
    attach_file: 'paperclip',
    insert_drive_file: 'file',
    folder_open: 'folder-open',
    create_new_folder: 'folder-plus',
    image: 'image',
    photo_camera: 'camera',
    volume_up: 'volume-2',
    play_arrow: 'play',
    skip_previous: 'skip-back',
    skip_next: 'skip-forward',
    cloud_upload: 'upload-cloud',
    cloud_download: 'download-cloud',
    cloud_off: 'cloud-off',
    wifi_off: 'wifi-off',
    battery_full: 'battery-full',
    battery_charging_full: 'battery-charging',
    signal_cellular_alt: 'signal',
    brightness_high: 'sun',
    brightness_low: 'moon',
    bug_report: 'bug',
    build: 'wrench',
    cached: 'refresh-cw',
    dns: 'server',
    storage: 'database',
    security: 'shield',
    verified_user: 'shield-check',
    fingerprint: 'fingerprint',
    error: 'x-circle',
    error_outline: 'alert-circle',
    info: 'info',
    help: 'help-circle',
    help_outline: 'help-circle',
    report_problem: 'alert-triangle',
    check_circle: 'check-circle',
    cancel: 'x-circle',
    block: 'ban',
    not_interested: 'minus-circle',
    thumb_up: 'thumbs-up',
    thumb_down: 'thumbs-down',
    sentiment_satisfied: 'smile',
    sentiment_dissatisfied: 'frown',
    group: 'users',
    person_add: 'user-plus',
    person_remove: 'user-minus',
    people: 'users',
    public: 'globe',
    translate: 'languages',
    trending_up: 'trending-up',
    trending_down: 'trending-down',
    show_chart: 'line-chart',
    bar_chart: 'bar-chart-3',
    pie_chart: 'pie-chart',
    attach_money: 'dollar-sign',
    money_off: 'ban',
    shopping_cart: 'shopping-cart',
    shopping_bag: 'shopping-bag',
    store: 'store',
    local_hospital: 'hospital',
    local_pharmacy: 'pill',
    healing: 'heart',
    medical_services: 'stethoscope',
    science: 'flask-conical',
    biotech: 'dna',
    psychology: 'brain',
    fitness_center: 'dumbbell',
    sports: 'trophy',
    'restaurant-outline': 'utensils-crossed',
    restaurant: 'utensils-crossed',
    'stats-chart-outline': 'line-chart',
    'stats-chart': 'line-chart',
    // Achievement icons
    'trophy-outline': 'trophy',
    trophy: 'trophy',
    'flame-outline': 'flame',
    flame: 'flame',
    'ribbon-outline': 'award',
    ribbon: 'award',
    // Tips page icons
    'bulb-outline': 'lightbulb',
    bulb: 'lightbulb',
    'walk-outline': 'footprints',
    walk: 'footprints',
    'happy-outline': 'smile',
    happy: 'smile',
    'footsteps-outline': 'footprints',
    footsteps: 'footprints',
    'people-outline': 'users',
    'nutrition-outline': 'apple',
    nutrition: 'apple',
    'fitness-outline': 'dumbbell',
    fitness: 'dumbbell',
    'paper-plane-outline': 'send',
    'paper-plane': 'send',
    // Missing dashboard icons
    track_changes: 'target',
    monitoring: 'activity',
    // Settings & Profile icons
    'color-palette': 'palette',
    'options-outline': 'sliders-horizontal',
    options: 'sliders-horizontal',
  };

  get mappedName(): string {
    // Return mapped name or original if no mapping exists
    return this.iconMappings[this.name] || this.name;
  }

  get computedSize(): number {
    const sizeMap = {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 32,
      xl: 48,
    };
    return sizeMap[this.size];
  }

  get computedClasses(): string {
    const sizeClasses = {
      xs: 'w-4 h-4',
      sm: 'w-5 h-5',
      md: 'w-6 h-6',
      lg: 'w-8 h-8',
      xl: 'w-12 h-12',
    };

    // Combine size classes with any custom classes
    const baseClasses = sizeClasses[this.size];
    return this.class ? `${baseClasses} ${this.class}` : baseClasses;
  }
}
