name: 'Setup pnpm'
description: 'Setup Node.js, pnpm, and install dependencies with caching'

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '24'
  pnpm-version:
    description: 'pnpm version'
    required: false
    default: '10.12.1'
  install:
    description: 'Run pnpm install'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install pnpm
      shell: bash
      run: corepack prepare pnpm@${{ inputs.pnpm-version }} --activate

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: inputs.install == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
